import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { AuthProvider } from "./Providers";
import { ReduxProvider } from "@/redux/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className="{inter.className} bg-gray-200">
            <AuthProvider>
                  <ReduxProvider>
                       <Navbar /> 
                       {children}
                  </ReduxProvider> 
            </AuthProvider>
       </body>
    </html>
  );
}
